import tkinter as tk
from tkinter import messagebox

# def abrirVentana1():
#     ventana.withdraw()
#     win1=tk.Toplevel()
#     global imagen2
#     win1.title("MENÚ")
#     win1.geometry("475x468")
#     win1.configure(background="snow")
#     imagen2=tk.PhotoImage(file="uni.png")
#     label2=tk.Label(win1,image=imagen2)
#     label2.place(x=0,y=0)
#     lbl3=tk.Label(win1,text=" ",font=("Arial",20), width=20, height=14, bg="firebrick3", fg="firebrick3")
#     lbl3.place(x=78,y=5)
#     lbl4=tk.Label(win1,text=" ", font=("Arial", 20), width=1, height=14, bg="gray", fg="gray")
#     lbl4.place(x=93,y=5)
#     lbl5=tk.Label(win1, text=" ", font=("Arial",20), width=1, height=14, bg="gray", fg="gray")
#     lbl5.place(x=368,y=5)
#     lbl6=tk.Label(win1,text="MENÚ", font=("Times New Roman", 25), width=5, height=1, bg="firebrick3", fg="firebrick3")
#     lbl6.place(x=188,y=20)
#     boton2=tk.Button(win1,text="DIAGRAMAS", font=("Times New Roman", 25), bg="snow", fg="gray")
#     boton2.place(x=163,y=90,width=150,height=30)
#     boton3=tk.Button(win1,text="STELLA", font=("Times New Roman",15),bg="snow",fg="gray")

win1=tk.Tk()
global imagen2
win1.title("MENÚ")
win1.geometry("400x450")
win1.configure(background="snow")
# imagen2=tk.PhotoImage(file="uni.png")
# label2=tk.Label(win1,image=imagen2)
# label2.place(x=0,y=0)
lbl3=tk.Label(win1,text=" ",font=("Arial",20), width=24, height=14, bg="firebrick3", fg="firebrick3")
lbl3.place(x=5,y=5)
lbl4=tk.Label(win1,text=" ", font=("Arial", 20), width=1, height=14, bg="gray", fg="gray")
lbl4.place(x=50,y=5)
lbl5=tk.Label(win1, text=" ", font=("Arial",20), width=1, height=14, bg="gray", fg="gray")
lbl5.place(x=330,y=5)
lbl6=tk.Label(win1,text="MENÚ", font=("Times New Roman", 25), width=5, height=1, bg="firebrick3", fg="white")
lbl6.place(x=155,y=20)
boton2=tk.Button(win1,text="DIAGRAMAS", font=("Times New Roman", 25), bg="snow", fg="gray")
boton2.place(x=100,y=90,width=200,height=30)
boton3=tk.Button(win1,text="STELLA", font=("Times New Roman", 25), bg="snow", fg="gray")
boton3.place(x=100,y=150,width=200,height=30)
boton4=tk.Button(win1,text="TABLAS", font=("Times New Roman", 25), bg="snow", fg="gray")
boton4.place(x=100,y=210,width=200,height=30)
win1.mainloop()
